"""Utility helpers for validation, history, reports, and notifications."""

from __future__ import annotations

import hashlib
import json
from datetime import datetime
from pathlib import Path
from typing import Optional


BASE_DIR = Path(__file__).resolve().parent
HISTORY_FILE = BASE_DIR / "prediction_history.json"
MAX_HISTORY = 50


def load_history() -> list:
    if not HISTORY_FILE.exists():
        return []
    try:
        return json.loads(HISTORY_FILE.read_text(encoding="utf-8"))
    except Exception:
        return []


def save_history(history: list) -> bool:
    try:
        HISTORY_FILE.write_text(json.dumps(history[-MAX_HISTORY:], indent=2), encoding="utf-8")
        return True
    except Exception:
        return False


def add_to_history(prediction_result: dict) -> list:
    history = load_history()
    entry = {
        "id": hashlib.md5(
            f"{prediction_result.get('timestamp', '')}{prediction_result.get('health_score', '')}".encode()
        ).hexdigest()[:8],
        "timestamp": prediction_result.get("timestamp", datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
        "health_score": prediction_result.get("health_score", 0),
        "health_status": prediction_result.get("health_status", "Unknown"),
        "risk_level": prediction_result.get("risk_level", "Unknown"),
        "input_summary": prediction_result.get("input_summary", {}),
    }
    history.append(entry)
    save_history(history)
    return history


def get_history_display() -> str:
    history = load_history()
    if not history:
        return "No predictions yet. Run your first analysis."

    lines = ["### Prediction History (Last 10)"]
    for entry in reversed(history[-10:]):
        score = entry.get("health_score", "N/A")
        status = entry.get("health_status") or entry.get("status") or "Unknown"
        risk = entry.get("risk_level", "Unknown")
        lines.append(
            f"**{entry.get('timestamp', 'Unknown time')}**  \n"
            f"Score: `{score}` | "
            f"Status: **{status}** | "
            f"Risk: {risk}"
        )
    return "\n\n".join(lines)


def validate_inputs(
    device_age: float,
    cores: int,
    cpu: float,
    ram: float,
    disk: float,
    running_apps: int,
    crashed_apps: int,
) -> tuple[bool, str]:
    errors = []
    if not 0 <= float(device_age) <= 20:
        errors.append("Device age must be between 0 and 20 years.")
    if not 1 <= int(cores) <= 32:
        errors.append("CPU cores must be between 1 and 32.")
    if not 0 <= float(cpu) <= 100:
        errors.append("CPU utilization must be between 0 and 100%.")
    if not 0 <= float(ram) <= 100:
        errors.append("Memory utilization must be between 0 and 100%.")
    if not 0 <= float(disk) <= 100:
        errors.append("Disk I/O must be between 0 and 100%.")
    if not 0 <= int(running_apps) <= 200:
        errors.append("Running apps must be between 0 and 200.")
    if not 0 <= int(crashed_apps) <= 50:
        errors.append("Crashed apps must be between 0 and 50.")
    if int(crashed_apps) > int(running_apps):
        errors.append("Crashed apps cannot exceed running apps.")

    if errors:
        return False, "\n".join(errors)
    return True, ""


def generate_text_report(prediction_result: dict) -> str:
    sep = "=" * 64
    thin_sep = "-" * 64
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    inputs = prediction_result.get("input_summary", {})
    alerts = prediction_result.get("alerts", [])
    recommendations = prediction_result.get("recommendations", [])

    report = f"""
{sep}
LAPTOP HEALTH PREDICTION REPORT
{sep}

Generated       : {now}
Health Score    : {prediction_result.get("health_score", "N/A")} / 100
Health Status   : {prediction_result.get("health_status", "Unknown")}
Risk Level      : {prediction_result.get("risk_level", "Unknown")}
Failure Risk    : {prediction_result.get("risk_percent", "N/A")}%
Model Confidence: {prediction_result.get("confidence", "N/A")}%

{thin_sep}
SYSTEM INPUTS
{thin_sep}
"""
    for key, value in inputs.items():
        report += f"{key:<18}: {value}\n"

    if alerts:
        report += f"\n{thin_sep}\nACTIVE ALERTS\n{thin_sep}\n"
        for alert in alerts:
            report += f"- {alert}\n"

    report += f"\n{thin_sep}\nRECOMMENDATIONS\n{thin_sep}\n"
    for index, item in enumerate(recommendations, 1):
        report += f"{index}. {item}\n"

    report += f"""

{thin_sep}
DISCLAIMER
{thin_sep}
This report is generated by an ML model and should be used as
decision support, not as a replacement for physical diagnostics.

{sep}
"""
    return report.strip()


def save_report_to_file(prediction_result: dict) -> Optional[str]:
    try:
        filename = BASE_DIR / f"health_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        filename.write_text(generate_text_report(prediction_result), encoding="utf-8")
        return str(filename)
    except Exception as exc:
        print(f"Report save error: {exc}")
        return None


def build_notification(prediction_result: dict) -> dict:
    score = float(prediction_result.get("health_score", 0))
    status = prediction_result.get("health_status", "Unknown")
    if score >= 85:
        return {"type": "success", "title": "System healthy", "message": f"Health Score: {score}/100 - {status}"}
    if score >= 70:
        return {"type": "info", "title": "Good condition", "message": f"Health Score: {score}/100 - minor tuning suggested"}
    if score >= 50:
        return {"type": "warning", "title": "Attention needed", "message": f"Health Score: {score}/100 - maintenance suggested"}
    if score >= 30:
        return {"type": "error", "title": "Poor health", "message": f"Health Score: {score}/100 - immediate action recommended"}
    return {"type": "critical", "title": "Critical alert", "message": f"Health Score: {score}/100 - system at risk"}
